# Generated by Django 2.2 on 2019-06-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petrol_detail',
            name='nepali_month',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
