# Generated by Django 2.2 on 2019-06-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_petrol_detail_nepali_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='petrol_detail',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
