# Generated by Django 2.2 on 2019-06-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190623_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='branch',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
